// Centralized error codes returned in ApiErrorResponse.error.code.
// Keep in sync with docs/api/README.md.
export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  REGISTRATION_INVALID: 'REGISTRATION_INVALID',
  CHECKPOINT_ALREADY_COMPLETED: 'CHECKPOINT_ALREADY_COMPLETED',
  CHECKPOINT_NOT_ASSIGNED: 'CHECKPOINT_NOT_ASSIGNED',
  CHECKPOINT_INACTIVE: 'CHECKPOINT_INACTIVE',
  QR_TOKEN_INVALID: 'QR_TOKEN_INVALID',
  QR_TOKEN_REVOKED: 'QR_TOKEN_REVOKED',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYMENT_PROVIDER_UNAVAILABLE: 'PAYMENT_PROVIDER_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Default HTTP status for each error code, used by the central error handler. */
export const ERROR_CODE_STATUS: Record<ErrorCode, number> = {
  AUTH_REQUIRED: 401,
  INVALID_CREDENTIALS: 401,
  FORBIDDEN: 403,
  RESOURCE_NOT_FOUND: 404,
  VALIDATION_ERROR: 422,
  DUPLICATE_RESOURCE: 409,
  PAYMENT_REQUIRED: 402,
  REGISTRATION_INVALID: 422,
  CHECKPOINT_ALREADY_COMPLETED: 409,
  CHECKPOINT_NOT_ASSIGNED: 403,
  CHECKPOINT_INACTIVE: 409,
  QR_TOKEN_INVALID: 422,
  QR_TOKEN_REVOKED: 409,
  RATE_LIMITED: 429,
  PAYMENT_PROVIDER_UNAVAILABLE: 503,
  INTERNAL_ERROR: 500,
};
