// Permission codes. Roles are granted permissions via the role_permissions
// table (see database/seed) — never hard-code "if role === ADMIN" checks
// in controllers; check permissions instead so the mapping stays admin-editable.
export const PERMISSIONS = {
  VIEW_ATTENDEE: 'VIEW_ATTENDEE',
  UPDATE_ATTENDEE: 'UPDATE_ATTENDEE',
  MANAGE_REGISTRATIONS: 'MANAGE_REGISTRATIONS',
  MANAGE_PAYMENTS: 'MANAGE_PAYMENTS',
  MANAGE_SPEAKERS: 'MANAGE_SPEAKERS',
  MANAGE_SESSIONS: 'MANAGE_SESSIONS',
  MANAGE_AGENDA: 'MANAGE_AGENDA',
  MANAGE_TIMELINE: 'MANAGE_TIMELINE',
  MANAGE_VENUES: 'MANAGE_VENUES',
  MANAGE_FAQ: 'MANAGE_FAQ',
  MANAGE_ANNOUNCEMENTS: 'MANAGE_ANNOUNCEMENTS',
  MANAGE_CHECKPOINTS: 'MANAGE_CHECKPOINTS',
  COMPLETE_CHECKPOINT: 'COMPLETE_CHECKPOINT',
  MANAGE_VOLUNTEERS: 'MANAGE_VOLUNTEERS',
  MANAGE_CERTIFICATES: 'MANAGE_CERTIFICATES',
  MANAGE_ACHIEVEMENTS: 'MANAGE_ACHIEVEMENTS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** Default role → permission grants, applied by the database seed. */
export const ROLE_PERMISSION_SEED: Record<'ADMIN' | 'VOLUNTEER' | 'ATTENDEE', PermissionCode[]> = {
  ADMIN: Object.values(PERMISSIONS),
  VOLUNTEER: [PERMISSIONS.VIEW_ATTENDEE, PERMISSIONS.COMPLETE_CHECKPOINT],
  ATTENDEE: [],
};
